name: cppo
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohttp=3.9.5=py310h8d17308_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - anaconda_prompt=1.1.0=haa95532_1
  - arrow=1.3.0=pyhd8ed1ab_1
  - astroid=3.3.11=py310haa95532_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - asyncssh=2.21.1=pyhd8ed1ab_0
  - atomicwrites=1.4.0=py_0
  - attrs=25.4.0=pyh71513ae_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=25.1.0=py310h5588dad_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli-python=1.1.0=py310h73ae2b4_4
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py310h29418f3_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.3.0=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cookiecutter=1.7.3=pyh6c4a22f_1
  - cryptography=46.0.3=py310he482ccc_0
  - debugpy=1.8.17=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.4.0=pyhd8ed1ab_0
  - docstring-to-markdown=0.17=pyhe01879c_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - flake8=7.1.1=py310haa95532_0
  - frozenlist=1.7.0=py310had1666a_0
  - glfw=3.4=hfd05255_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6c2663c_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.37.0=pyha7b4d00_0
  - isort=6.1.0=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jedi=0.19.2=pyhd8ed1ab_1
  - jellyfish=1.1.3=py310hc226416_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jinja2-time=0.2.0=pyhd8ed1ab_4
  - jpeg=9f=ha349fce_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - keyring=24.3.1=pyh7428d3b_1
  - krb5=1.20.1=h5b6d351_0
  - libabseil=20230125.0=cxx17_h63175ca_1
  - libblas=3.9.0=35_h5709861_mkl
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libccd-double=2.1=h63175ca_3
  - libclang=14.0.6=default_hb5a9fac_2
  - libclang13=14.0.6=default_h8e68704_2
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - libmujoco=2.3.3=h177ed3a_0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libsodium=1.0.20=h83e8143_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libuv=1.48.0=h827c3e9_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.3=hfa2b4ca_0
  - lodepng=20220109=h2d74725_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.3=py310hdb0e946_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2024.2.2=h57928b3_16
  - more-itertools=10.8.0=pyhd8ed1ab_0
  - mujoco=2.3.3=h57928b3_0
  - mujoco-python=2.3.3=py310h73e4b6c_0
  - multidict=6.6.3=py310hdb0e946_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpydoc=1.9.0=pyhe01879c_1
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.2=pyhc872135_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - poyo=0.5.0=pyhd8ed1ab_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd3eb1b0_0
  - propcache=0.3.1=py310h38315fa_0
  - psutil=7.1.0=py310h29418f3_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.1=pyhd8ed1ab_0
  - pyglfw=2.10.0=pyha770c72_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pylint=3.3.9=pyhcf101f3_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.6.0=py310h29418f3_0
  - pyopengl=3.1.10=pyh7428d3b_2
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyqt=5.15.10=py310h5da7b33_1
  - pyqt5-sip=12.13.0=py310h827c3e9_1
  - pyqtwebengine=5.15.10=py310h5da7b33_1
  - pyrsistent=0.20.0=py310h29418f3_2
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.18=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gssapi=1.8.3=py310hbb35dff_2
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-server=1.12.2=py310hbc747e5_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python_abi=3.10=2_cp310
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyuca=1.2=pyhd8ed1ab_2
  - pywin32=311=py310h282bd7d_1
  - pywin32-ctypes=0.2.3=py310h5588dad_2
  - pyyaml=6.0.3=py310hdb0e946_0
  - pyzmq=27.1.0=py310h535538e_0
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qhull=2020.2=hc790b64_5
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.2=h19c9488_12
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtconsole=5.6.1=py310haa95532_1
  - qtpy=2.4.3=pyhd8ed1ab_1
  - requests=2.32.5=pyhd8ed1ab_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rtree=1.4.1=pyh11ca60a_0
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.7.12=py310h00ffb61_0
  - six=1.17.0=pyhe01879c_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.8=pyhd8ed1ab_0
  - sphinx=8.1.3=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-devhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-serializinghtml=2.0.0=pyhd3eb1b0_0
  - spyder=6.0.5=py310haa95532_0
  - spyder-kernels=3.0.5=py310hbc747e5_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.6=pyhb6d5dde_0
  - tbb=2021.13.0=h18a62a1_3
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.6.3=pyhd8ed1ab_1
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tinyxml2=9.0.0=h0e60522_2
  - tk=8.6.15=hf199647_0
  - tomli=2.3.0=pyhcf101f3_0
  - tomlkit=0.13.3=pyha770c72_0
  - tornado=6.5.2=py310h29418f3_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20251008=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - ujson=5.11.0=py310h699e580_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py310h5588dad_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.3=py310h29418f3_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.20.1=py310h38315fa_0
  - zeromq=4.3.5=h6c54ac7_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.25.0=py310h1637853_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - deprecated==1.2.18
      - etils==1.13.0
      - farama-notifications==0.0.4
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gymnasium==0.28.1
      - gymnasium-robotics==1.2.2
      - imageio==2.37.0
      - jax-jumpy==1.0.0
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==1.23.5
      - pettingzoo==1.25.0
      - pillow==11.3.0
      - pygame==2.1.0
      - pyparsing==3.2.5
      - qtawesome==1.4.0
      - safety-gymnasium==1.0.0
      - sympy==1.13.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - xmltodict==1.0.2
prefix: C:\Users\13004\anaconda3\envs\cppo
